Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.10.2', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 832, in main
    make_or_verify_needed_dirs(config)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 788, in make_or_verify_needed_dirs
    os.geteuid(), config.strict_permissions)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 781, in make_or_verify_core_dir
    raise errors.Error(_PERM_ERR_FMT.format(error))
Error: The following error was encountered:
[Errno 13] Permission denied: '/var/lib/letsencrypt'
If running as non-root, set --config-dir, --logs-dir, and --work-dir to writeable paths.
